Removing CLANG_MODULE setting. rdar://124559419
Reviewed by Elliot Williams.

Looks like it's not really needed for Swift interop.
Newer versions of clang are causing the build to fail otherwise.

Error:
In file included from /Volumes/Data/safari-4/OpenSource/Source/WebCore/PAL/pal/text/TextCodecLatin1.cpp:31:
/Volumes/Data/safari-4/OpenSource/WebKitBuild/Debug/usr/local/include/wtf/text/CString.h:77:17: error: definition of 'basic_string' must be imported from module 'std_string' before it is required
   77 |     std::string toStdString() const { return m_buffer ? std::string(m_buffer->data()) : std::string(); }
      |
* Source/WebCore/PAL/Configurations/PAL.xcconfig:

Canonical link: https://commits.webkit.org/276112@main