Fails to build with GCC 13 due to overloaded-virtual error in FilterEffect https://bugs.webkit.org/show_bug.cgi?id=259729
Reviewed by Said Abou-Hallawa.

FilterEffect.h:44:18: error: ‘virtual bool WebCore::FilterEffect::operator==(const WebCore::FilterEffect&) const’ was hidden [-Werror=overloaded-virtual=]
   44 |     virtual bool operator==(const FilterEffect&) const;
      |                  ^~~~~~~~
FELighting.h:42:10: note:   by ‘bool WebCore::FELighting::operator==(const WebCore::FELighting&) const’
   42 |     bool operator==(const FELighting&) const;
      |          ^~~~~~~~

* Source/WebCore/platform/graphics/filters/FELighting.h:

Canonical link: https://commits.webkit.org/266539@main