WKFullScreenWindowControllerIOS.mm:1296:19: error: variable 'manager' set but not used [-Werror,-Wunused-but-set-variable] <https://bugs.webkit.org/show_bug.cgi?id=292449> <rdar://150538262>
Unreviewed build fix reviewed by Darin Adler.

* Source/WebKit/UIProcess/ios/fullscreen/WKFullScreenWindowControllerIOS.mm:
(-[WKFullScreenWindowController exitFullScreen:]):
- Remove local `manager` variable since we only need to check `self._manager`
  after the changes in 290551@main for Bug 287803.

Canonical link: https://commits.webkit.org/294441@main