Error: redefinition of 'gigacageEnabledForProcess' in JSCOnly MacOS Ports https://bugs.webkit.org/show_bug.cgi?id=245295 rdar://problem/100133724
Reviewed by Mark Lam.

The BPLATFORM guard around `gigacageEnabledForProcess()` in ProcessCheck.h does not match the guard
in ProcessCheck.mm. This breaks the JSCOnly variant of the bmalloc build on Darwin since the JSCOnly
variant doesn't define a BPLATFORM macro.

Fix this by making the guards match.

* Source/bmalloc/bmalloc/ProcessCheck.mm:

Canonical link: https://commits.webkit.org/254658@main