REGRESSION(271118@main): CheckboxInputType.cpp should include RenderStyleInlines.h https://bugs.webkit.org/show_bug.cgi?id=265108
Unreviewed build fix. Windows port debug builds can't compile after
271118@main with the following error.

> WebCore\rendering\style\RenderStyle.h(381,17): error: inline function 'WebCore::RenderStyle::hasEffectiveAppearance' is not defined [-Werror,-Wundefined-inline]
>   381 |     inline bool hasEffectiveAppearance() const;
>       |                 ^
> WebCore\html/CheckboxInputType.cpp(143,43): note: used here
>   143 |     ASSERT(element()->renderer()->style().hasEffectiveAppearance());
>       |                                           ^

* Source/WebCore/html/CheckboxInputType.cpp:

Canonical link: https://commits.webkit.org/271125@main