REGRESSION(281176@main): [PlayStation] OSAllocatorPlayStation.cpp:142:19: error: expected '}' https://bugs.webkit.org/show_bug.cgi?id=276850
Unreviewed build fix.

* Source/WTF/wtf/playstation/OSAllocatorPlayStation.cpp:
Added a missing '}'.

Canonical link: https://commits.webkit.org/281181@main