REGRESSION(285102@main): Fix a compiler error of AXObjectCacheWin.cpp
Unreviewed build fix for Windows port Debug builds.

> win/AXObjectCacheWin.cpp(118,29): error: no member named 'toUInt64' in
>     'std::optional<WTF::ObjectIdentifierGeneric<WebCore::AXIDType, WTF::ObjectIdentifierMainThreadAccessTraits<uint64_t>, unsigned long long, WTF::SupportsObjectIdentifierNullState::No>>';
>         did you mean to use '->' instead of '.'?

* Source/WebCore/accessibility/win/AXObjectCacheWin.cpp:
(WebCore::AXObjectCache::postPlatformNotification):

Canonical link: https://commits.webkit.org/285121@main