Unreviewed, fix iOS production builds after 270071@main
Fix the following build error:
```
Undefined symbols for architecture arm64e:
  "_JSContextGetGlobalObject", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
      WTR::hasTestWaitAttribute(OpaqueJSContext*) in WPTFunctions.o
  "_JSObjectMake", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
  "_JSValueProtect", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
  "_JSValueToBoolean", referenced from:
      WTR::hasTestWaitAttribute(OpaqueJSContext*) in WPTFunctions.o
  "_JSValueUnprotect", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
  "WTR::setProperty(OpaqueJSContext const*, OpaqueJSValue*, char const*, bool)", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
  "WTR::objectProperty(OpaqueJSContext const*, OpaqueJSValue*, std::initializer_list<char const*>)", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o

 WTR::hasTestWaitAttribute(OpaqueJSContext*) in WPTFunctions.o
  "WTR::callConstructor(OpaqueJSContext*, char const*, std::initializer_list<OpaqueJSValue const*>)", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
  "WTR::call(OpaqueJSContext const*, OpaqueJSValue*, char const*, std::initializer_list<OpaqueJSValue const*>)", refe
renced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
      WTR::hasTestWaitAttribute(OpaqueJSContext*) in WPTFunctions.o
  "WTR::makeValue(OpaqueJSContext const*, char const*)", referenced from:
      WTR::sendTestRenderedEvent(OpaqueJSContext*) in WPTFunctions.o
      WTR::hasTestWaitAttribute(OpaqueJSContext*) in WPTFunctions.o
  "WTF::URL::host() const", referenced from:
      WTR::isWebPlatformTestURL(WTF::URL const&) in WPTFunctions.o
  "WTF::URL::port() const", referenced from:
      WTR::isWebPlatformTestURL(WTF::URL const&) in WPTFunctions.o
ld: symbol(s) not found for architecture arm64e
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

...by removing `WPTFunctions.o` from the `WebKitTestRunner` binary
target. This is the correct thing to do because we pull in the symbols
in the `WPTFunctions` TU through the `WebKitTestRunnerLibrary` target
anyways, and because we don't link against WTF/JSC/etc. when building
the `WebKitTestRunner` binary on iOS.

* Tools/WebKitTestRunner/WebKitTestRunner.xcodeproj/project.pbxproj:

Canonical link: https://commits.webkit.org/270093@main