REGRESSION(261710@main) Unreviewed build fix for non-Cocoa ports https://bugs.webkit.org/show_bug.cgi?id=253837
> WebProcess/WebPage/DrawingArea.cpp(266): error C2065: 'LOG_CHANNEL_PREFIXResize': undeclared identifier

* Source/WebKit/WebProcess/Notifications/WebNotificationManager.cpp:
* Source/WebKit/WebProcess/WebPage/DrawingArea.cpp:
Added include "Logging.h".

Canonical link: https://commits.webkit.org/261715@main