Add PlatformDynamicRangeLimit::ValueType to abstract the value&storage type https://bugs.webkit.org/show_bug.cgi?id=291621 rdar://149364934
Reviewed by Mike Wyrzykowski.

Use PlatformDynamicRangeLimit::ValueType instead of naked float.
This will make future changes simpler and clearer.

Exception: The private 3-float constructor still takes floats, because
that won't change even if/when ValueType changes.

* Source/WebCore/platform/graphics/PlatformDynamicRangeLimit.cpp:
(WebCore::PlatformDynamicRangeLimit::normalizedAverage):
* Source/WebCore/platform/graphics/PlatformDynamicRangeLimit.h:
(WebCore::PlatformDynamicRangeLimit::value const):
(WebCore::PlatformDynamicRangeLimit::PlatformDynamicRangeLimit):
* Tools/TestWebKitAPI/Tests/WebCore/PlatformDynamicRangeLimitTests.cpp:

Canonical link: https://commits.webkit.org/293945@main