REGRESSION(254322@main) PlatformCAAnimationWin.cpp(550,86): error C2660: 'CFArrayAppendValue': function does not take 1 arguments https://bugs.webkit.org/show_bug.cgi?id=245052
Unreviewed build fix.

* Source/WebCore/platform/graphics/ca/win/PlatformCAAnimationWin.cpp:
(PlatformCAAnimationWin::setTimingFunctions):

Canonical link: https://commits.webkit.org/254385@main