REGRESSION(284303@main): UIProcess/ProcessThrottler.cpp(318,25): error: unused variable 'probableWakeupReason' https://bugs.webkit.org/show_bug.cgi?id=280432
Reviewed by Chris Dumez.

Windows port couldn't compile with clang-19 after
<https://commits.webkit.org/284303@main>. 'probableWakeupReason' was
an unused variable if RELEASE_LOG_DISABLED. It doesn't support
RELEASE_LOG yet.

* Source/WebKit/UIProcess/ProcessThrottler.cpp:
(WebKit::ProcessThrottler::updateThrottleStateIfNeeded):
Conditioned out the code with !RELEASE_LOG_DISABLED.

Canonical link: https://commits.webkit.org/284318@main