REGRESSION(269701@main): Unreviewed build fix for Windows port https://bugs.webkit.org/show_bug.cgi?id=263566
> WebProcess/GPU/graphics/WebGPU/RemoteDeviceProxy.cpp(158,30): error: use of undeclared identifier 'convertedDescriptor'

* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteDeviceProxy.cpp:

Canonical link: https://commits.webkit.org/269702@main