REGRESSION(263570@main) [Win] Connection.cpp: error C2121: '#': invalid character: possibly the result of a macro expansion https://bugs.webkit.org/show_bug.cgi?id=256181
Unreviewed build fix for Windows port.

> WebKit/Platform/IPC/Connection.cpp(577): error C2121: '#': invalid character: possibly the result of a macro expansion

* Source/WebKit/Platform/IPC/Connection.cpp:
(IPC::Connection::sendMessage):
Don't use #if in RELEASE_LOG_ERROR.

Canonical link: https://commits.webkit.org/263574@main