Unreviewed, fix the Mac Catalyst build after 276475@main rdar://125189906
Add a missing `#import "MessageSenderInlines.h"` to fix a linker error that began after unified
source ordering caused this Catalyst-specific file to lose the `MessageSender` inlines:

```
Undefined symbols for architecture arm64e:
  "bool IPC::MessageSender::send<Messages::TextCheckingControllerProxy::ReplaceRelativeToSelection>( … )", referenced from:
      WebKit::TextCheckingController::replaceRelativeToSelection( … ) in
  "bool IPC::MessageSender::send<Messages::TextCheckingControllerProxy::RemoveAnnotationRelativeToSelection>( … )", referenced from:
      WebKit::TextCheckingController::removeAnnotationRelativeToSelection( … ) in
ld: symbol(s) not found for architecture arm64e
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

* Source/WebKit/UIProcess/Cocoa/TextCheckingController.mm:

Canonical link: https://commits.webkit.org/276545@main