Unreviewed, fix iOS engineering builds after 269802@main
Fix the following build error:

```
TestWebKitAPI Ld TestWebKitAPI
Undefined symbols for architecture arm64e:
  "_CGImageDestinationAddImage", referenced from:
      WebKit::transcode(CGImage*, __CFString const*) in libWebKitPlatform.a(PlatformUnifiedSource1-mm.o)
  "_CGImageDestinationCreateWithData", referenced from:
      WebKit::transcode(CGImage*, __CFString const*) in libWebKitPlatform.a(PlatformUnifiedSource1-mm.o)
  "_CGImageDestinationFinalize", referenced from:
      WebKit::transcode(CGImage*, __CFString const*) in libWebKitPlatform.a(PlatformUnifiedSource1-mm.o)
  "_CGImageSourceCreateImageAtIndex", referenced from:
      WebKit::requestBackgroundRemoval(CGImage*, WTF::CompletionHandler<void (CGImage*)>&&) in libWebKitPlatform.a(PlatformUnifiedSource1-mm.o)
  "_CGImageSourceCreateWithData", referenced from:
      WebKit::requestBackgroundRemoval(CGImage*, WTF::CompletionHandler<void (CGImage*)>&&) in libWebKitPlatform.a(PlatformUnifiedSource1-mm.o)
ld: symbol(s) not found for architecture arm64e
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

...by linking against ImageIO in configurations where `ENABLE(IMAGE_ANALYSIS_ENHANCEMENTS)` is set.

* Tools/TestWebKitAPI/Configurations/TestWebKitAPI.xcconfig:

Canonical link: https://commits.webkit.org/269862@main