REGRESSION(257606@main): WebProcess::didClose fix ENABLE_VIDEO=OFF
https://bugs.webkit.org/show_bug.cgi?id=249462

Reviewed by Philippe Normand.

No HTMLMediaElement is defined if video support is not compiled.

```
In file included from /home/buildbot/buildbot/slave-buildroot/build/output/build/webkitgtk-2.39.3/DerivedSources/WebKit/unified-sources/UnifiedSource-54928a2b-1.cpp:2:
/home/buildbot/buildbot/slave-buildroot/build/output/build/webkitgtk-2.39.3/Source/WebKit/WebProcess/WebProcess.cpp: In member function ‘virtual void WebKit::WebProcess::didClose(IPC::Connection&)’:
/home/buildbot/buildbot/slave-buildroot/build/output/build/webkitgtk-2.39.3/Source/WebKit/WebProcess/WebProcess.cpp:949:58: error: incomplete type ‘WebCore::HTMLMediaElement’ used in nested name specifier
  949 |     FileSystem::markPurgeable(WebCore::HTMLMediaElement::mediaCacheDirectory());
      |                                                          ^~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>

Canonical link: https://commits.webkit.org/258052@main