Add --max-bundle-size switch to generate-unified-source-bundles.rb https://bugs.webkit.org/show_bug.cgi?id=249797
Reviewed by Don Olmstead.

WinCairo-EWS bots are randomly failing to compile WebCore's unified
source due to "fatal error C1060: compiler is out of heap space".
248190@main (bug#237617) increased MAX_BUNDLE_SIZE to 16 only for
Windows to work around WinCairo.lib library size problem. However,
WinCairo is no longer creating the static library WinCairo.lib since
257608@main.

* Source/WTF/Scripts/generate-unified-source-bundles.rb: Added `--max-bundle-size` switch.
* Source/cmake/WebKitMacros.cmake: Append "--max-bundle-size 16"
  switches if MSVC and WebCore is a static library.

Canonical link: https://commits.webkit.org/258502@main