Update ANGLE to 2022-06-28 (2a5193f6ceca4c8a7f27b324ad7da4aa60f968b3) https://bugs.webkit.org/show_bug.cgi?id=242055
Reviewed by Dean Jackson.

Contains upstream commits:
git log --oneline b6a93d753bdd819ddc0dacb8cea554c86bc4c04e..2a5193f6ceca4c8a7f27b324ad7da4aa60f968b3 --pretty=%h %s
2a5193f6c Textures: Allow compressed texture from PBO
1ae9756e2 Textures: Centralize texture format emulation check
c775dd498 Allow list of restricted traces to be overriden in gn args
1c8256214 Roll Chromium from 8fdbb85c2176 to 1bfae54dd233 (738 revisions)
2adb6327e Add a pls test for memoryless storage
f86904290 Revert "Vulkan: Destroy DescriptorSet cache when it becomes invalid"
f5aef0112 Skip CreateFramebufferFetchMidRenderPass on Win SwANGLE
46ddcc440 Revert "Vulkan: Support EGL_ANDROID_front_buffer_auto_refresh"
10f065e2d Vulkan: support QCOM_shading_rate on Intel graphics
8f6889a11 Roll Chromium from 7f32e27c6969 to 8fdbb85c2176 (321 revisions)
ef37e8637 Skip TextureSampleShadingTest.Basic on Win Intel Vulkan
89e38b579 Refactor to use ANGLETest vs ANGLETestWithParam
de109f9ef Metal: Maintain BufferPool freelist constraint
707323c14 Miscellaneous C++17 refactoring
ef60d38ec Vulkan: Support EGL_ANDROID_front_buffer_auto_refresh
7eb96f2a3 Refactor builtin symbol generation for C++17
4c5e9d476 Do not defer clear if FBO attachment is AHB image
d3e4e9ee5 Roll vulkan-deps from 1765af41ecf5 to 11ad77222bfe (3 revisions)
722c78b0f Roll Chromium from 19706bf6c7d2 to 7f32e27c6969 (707 revisions)
79185677c Translator: Fix validation of struct with same-name struct field
e50351cb0 Vulkan: Don't close render pass on framebuffer fetch
919763526 Use C++17 attributes instead of custom macros
0779ccbcd Vulkan: Destroy DescriptorSet cache when it becomes invalid
669d7b756 Fix validation checks in glCompressedTexSubImage3D
338c65393 Set pixel unpack state in GL backend's CompressedTexImage3D.
97e0157a6 Fix compilation errors with deprecated sprintf function
6c8bb1f31 Metal: Fix invalid iosurface texture after base/max lvl changed
32cb57503 Roll SwiftShader from 5cb6a639d494 to ec31f547750c (3 revisions)
6d3c63705 Vulkan: Fix 180 and 270 degree rotated resolve
72f69e847 ANGLEPerfTest: Add option to disable GL debug callbacks.
c93b3b32d Tests: Add Animal Crossing trace.
329e1f9e1 Ensure pls results are secure even without barriers
21a07210e Suppress 3 pointcoord tests on Mac Intel Metal
9a6ae13ec Vulkan: Enable prerotation on multisample tests
593ef4c04 Switch Mac experimental testing to Intel
683209c42 Context: Limit max samples to 4 during capture.
dfbdc3513 Run trace_tests on DEPS changes
34f699470 Roll SwiftShader from ff5356238d86 to 5cb6a639d494 (2 revisions)
997c6833c Roll Chromium from de4095cef87e to 19706bf6c7d2 (495 revisions)
d55e06557 Add pls tests for fragment reject utilities
714f680f7 Implement GL_EXT_base_instance
be78a0feb Capture/Replay: Fix which sync object is deleted
32c38e55e Roll vulkan-deps from 45c701a7067d to 1765af41ecf5 (6 revisions)
072b155a6 Roll SwiftShader from f833544ff898 to ff5356238d86 (5 revisions)
1aaa61dcb Roll Chromium from 36bd948bdb66 to de4095cef87e (273 revisions)
21c89c148 Roll SwiftShader from 2b79b2f8aec2 to f833544ff898 (8 revisions)
59b9dde09 Roll vulkan-deps from 4ede36c4734b to 45c701a7067d (2 revisions)
9ea490f54 Roll Chromium from 58c59e887244 to 36bd948bdb66 (551 revisions)
878bbfaac Vulkan: Account for 2DArray textures during robust resource init
7f57d12b1 Vulkan: Disable cache warmup on ChromeOS SwANGLE
c59a22e58 Skip CompressedTexSubImage3DValidationPerSlice capture_replay
2d5b76cf9 Roll vulkan-deps from 21fa1f0acbfa to 4ede36c4734b (10 revisions)
0a7cfa083 Vulkan: Fix marking external images as renderable
ca96cba9c Make ReadEntireFileToString return a std::string.
5f1d0742f Increase batch timeout with sanitizer
88de1405e Revert "Temporarily remove win-trace from CQ"
872d7947b Roll SwiftShader from cfcb44322bcc to 2b79b2f8aec2 (1 revision)
a8b64f2f8 Roll Chromium from 96b247286bab to 58c59e887244 (150 revisions)
6ca9c55e6 Capture/Replay: Allow capturing of external textures
ea3bd30a6 Capture/Replay: Don't capture tex levels that are out-of-range
7ac73cc1e Roll VK-GL-CTS from 893946636054 to e22ec5fc4cbf (13 revisions)
5975eb034 Roll Chromium from e6f032b42bce to 96b247286bab (303 revisions)
72e457fee Vulkan: Promptly destroy cached framebuffer when it becomes invalid
bcc39a325 Enable ExposeNonConformantExtensionsAndVersions
6edb385b2 Roll VK-GL-CTS from 50754c3c19c0 to 893946636054 (1 revision)
97a6e5819 Vulkan: Useful implementation of program binaries
0bc70e96e Vulkan: Rename getShareGroupVk to getShareGroup
8a8b96656 Vulkan: Prune superseded staged updates in a texture
1131f1174 Support BGRX8 for framebuffer blits
c41dae02d Further suppress MultithreadingTestES3 hanging tests on Linux SwANGLE
f427ae416 Temporarily remove win-trace from CQ
a62204c35 Guard all imports of wayland.gni with angle_use_wayland
44b177433 Roll SwiftShader from 20c04524ee8a to cfcb44322bcc (4 revisions)
816a1b3ae Roll Chromium from c8885f7596b7 to e6f032b42bce (339 revisions)
9ebc1b6ae Roll vulkan-deps from 1762849caed4 to 21fa1f0acbfa (11 revisions)
3faaded82 Missing include for std::isdigit
a471d4bda Ensure ANGLERenderTest.mTestParams lifetime using unique_ptr
9d08c29a9 Expose the EGL Display Context Set in the DisplayState.
153d8db9d Turn missing {trace_name}.json trace files into test failures.
a9a14043f Roll Chromium from 664494793778 to c8885f7596b7 (146 revisions)
c2220ecf1 Always log FATAL, ERR messages
3c81c9d15 Enable perFrameWindowSizeQuery on Android
15376d4ec Roll Chromium from 41a77d56876c to 664494793778 (497 revisions)
b257d62cd Add GL_NV_read_depth_stencil
bd1722bcc Roll SwiftShader from ee0d0b41a626 to 20c04524ee8a (21 revisions)
1adf46a60 Enable X11 defines on ChromeOS
39df42d3f Vulkan: set storage external memory before the description
543dcdde5 GN: Wayland build overrides
5a3e1dba8 Skip flaky hanging MultithreadingTestES3 on Linux SwANGLE
c31e783fb Roll Chromium from 66a3aa3f63de to 41a77d56876c (471 revisions)
7c01db8f9 Add tests for loadOps in pixel local storage
f1c21d688 Add pixel local storage tests for all supported formats
59476401f Missing include for std::toupper
c5ee5a9c4 Vulkan: Add test CreateDestroyTextureDoesNotIncreaseDescSetCache
fd1317a70 Capture/Replay: capture GetProgramBinaryOES parameters
fec66d30d Skip 4 end2end tests flaky on Mac NVIDIA GL
bc72cf609 Roll vulkan-deps from cb1ab827eb4c to 1762849caed4 (2 revisions)
c8c474a35 Roll Chromium from 0c0e20acbce5 to 66a3aa3f63de (505 revisions)
f33f6aa8d Capture/Replay: Skip multithreading tests that time out
45c57333b Roll VK-GL-CTS from 8817dcf9c1ec to 50754c3c19c0 (11 revisions)
1c1b2a528 Suppress failing test
198924c46 Remove python 2 from presubmit
685d91759 Remove the build flag -Wno-deprecated-declarations
c73ea49a7 Reland "Remove cwd manipulations."
9797401b5 Tests: Add Star Wars: KOTOR trace
89aa1027b Specify display to EGL query in print info test.
81585fe20 Use consistent test names with dEQP.
d48c987ae Roll vulkan-deps from 00594ab942b5 to cb1ab827eb4c (11 revisions)
3cdd49750 Roll Chromium from ae46affd7997 to 0c0e20acbce5 (165 revisions)
3dfc80043 Vulkan: Optimize sync followed by swap
48195ae67 Roll Chromium from 4658acb376d4 to ae46affd7997 (1334 revisions)
4c6d47c80 Vulkan: Optimize glEGLImageTargetTexture2DOES with same args
ce78f5f8d Capture/Replay: Reset default uniforms
a894cb948 Bootstrap pixel local storage
ee1dd7f4a Vulkan: Add test for glEGLImageTargetTexture2DOES issue
715175de8 Vulkan: Don't enable Qualcomm workarounds on OSS driver
da9390d68 Vulkan: Fix the VulkanRenderPassBufferCount overlay widget
0408b1293 Overlay: Support globbing
2587e5088 Vulkan: Remove redundant vertex array dirty bit processing
76e98ae11 Roll VK-GL-CTS from acf70aaf3fdb to 8817dcf9c1ec (36 revisions)
0f8f760d9 Disable KHR_no_error for Android/SwiftShader
5fbb04176 Vulkan: Handling VK_EXT_load_store_op_none on ARM
d47c8e0a1 Vulkan: Enable custom border colors on SwiftShader
4b9eb4bac Optionally support vulkan_memory_allocator 3.x
f6517f307 infra: Remove linux-tsan-test from CQ
4e37ec8c0 Revert "Remove cwd manipulations."
07a6f0b23 Removes uses of sprintf() in ceval.
48b928d98 Vulkan: Overlay widgets for pipeline cache/hit stats
c11af00ae Remove cwd manipulations.
a65af0469 De-template out dEQP GTest bridge class.
1834902fc Revert "GL: Temporarily enable validation for all GL calls."
f06292ae4 Roll vulkan-deps from 23b710f1a0b3 to 00594ab942b5 (41 revisions)
4ea62009c Vulkan: Prefer driver uniforms over spec consts
9e47438ff Vulkan: Fix program creation crash
06ff0e3cb Implement GL_EXT_base_instance
b4d4231b7 infra: Increase shards for end2end tests on ASAN
b9bdc53ba Make TestEventListener and inner class of TestSuite.
43c45bc65 infra: Add Linux AMD test spec.
d670b5a36 GL: Disable texture border clamp on imagination.
d9a2027ff Add a test for volatile aliases of the same shader image
68634d5c7 Vulkan: Enable VK_EXT_platform_wayland
34d309306 Tests: Add Shadow Fight 3 trace.
52e560eae Remove suppressions for now-passing ES 3.1 tests.
35839293a Vulkan: Fix mutable format check
4dde8590e Remove suppression for passing tests
3b988fef3 Vulkan: Remove enableLineRasterEmulation
593cd597a Roll Chromium from 4697545681bd to 4658acb376d4 (377 revisions)
d66d9e7b1 Tests: Add Rush Royale trace.
aac68adcf Capture/Replay: Track dirty state per EntryPoint for Reset
cb9e1235f D3D11: fix UAV handling.
0260255b4 Fix printing of non-standard renderers.
4b911686c Converts from sprintf() to snprintf().
ce3c0fe90 Vulkan: Make depth-correction uniform controlled
4868e5a70 Log the fully formatted message for internal errors.
b186991a5 Vulkan: Remove non-current vertex array from buffer's observer list
2fcf9a929 Suppress failing test
b7bd08080 Support running end2end tests.
28c59d634 Vulkan: Fix Wayland Display DRM formats
b71c64275 Add a wrapper script to run traces using android_helper.
611f0e0d8 Roll Chromium from 113f00d1a057 to 4697545681bd (509 revisions)
7fb021b08 Reland "Add Vulkan backend support for texture labels"
ccf53e3d1 Translator/HLSL: fix image load/store handling.
2fec519f6 Avoid dirty texture swizzle state when there is no change
d655ad292 Vulkan: Add tests for FramebufferCache growth bugs
a95168651 Vulkan: Output cache look up feedback in pipeline graph
bfab7e60a Ignore eglBind/ReleaseTexImage calls for lost contexts.
ebdbae9b7 crash_handler_posix: Fix symbol path resolution.
ee338504a Roll Chromium from 795b7900dc69 to 113f00d1a057 (497 revisions)
cdad93636 crash_handler_posix: Use execvp.
415ff51b8 Metal: Remove use of ANGLE_MTL_AUTORELEASE from mtl_state_cache
53ec886e4 Vulkan: Externally synchronize the pipeline cache
2f6dcf773 Metal shaders fail to compile with "error: unknown type name 'uint'
eb282de02 Vulkan: Add feature to use VK_FILTER_LINEAR for YUVConversionInfo
bbf67e2e4 Capture/Replay: support capturing eglCreateImage/eglDestroyImage
73b7534be Vulkan: Suppress forced-xfb-emulation tests on pixel 6
94320a83a Metal: Validate total bits used in color attachments
f8f84e495 Roll SwiftShader from 466e443100e6 to ee0d0b41a626 (2 revisions)
67a8c1984 Roll Chromium from f6e0343d6b36 to 795b7900dc69 (491 revisions)
6a0c779eb Uptream Vivante and VMWare vendor ID recognition.
e04314fd8 Vulkan: Include state in pipeline graph dump
8a0351a5a Metal:Dynamically choose max draw buffers.
17f9e941a Metal: Upstream clear performance fix
e70bea8a6 Metal: Update MAX_LOD_BIAS
32a0ee929 Code Cleanup
6c0d46588 D3D11: implement stencil texturing.
28b4c378d Vulkan: Pipeline creation feedback in perf counters
b0d75fb5c Vulkan: Use 64-bit counters
53fb57a6d Vulkan: Fix xfb emulation bug w.r.t array elements
5a2cc71c2 Update extension support (June 1, 2022).
b03f27892 Revert "Use a temporary timeout multipler for trace tests."
4784f091d Roll vulkan-deps from 59aa5963cf64 to 23b710f1a0b3 (6 revisions)
f5b3baf89 Roll SwiftShader from 51c43dc015b7 to 466e443100e6 (2 revisions)
e14cd3700 Roll Chromium from 85bb5555c93e to f6e0343d6b36 (473 revisions)
9800a3cf3 Add a test for imageLoad after glClear to the texture
da30caec1 Vulkan: Switch resource tracking.
1ce69722a Vulkan: Track used command buffers in ResourceUse.
43b5311f1 D3D11: minor cleanup to getSRVLevel().

Canonical link: https://commits.webkit.org/251947@main