REGRESSION(266606@main): MessageArgumentDescriptions.cpp: Cannot open include file: 'WebExtensionContextIdentifier.h' https://bugs.webkit.org/show_bug.cgi?id=259839
Windows Debug builds were failing. Unreviewed build fix.

> WebKit\DerivedSources\MessageArgumentDescriptions.cpp(84): fatal error C1083: Cannot open include file: 'WebExtensionContextIdentifier.h': No such file or directory

* Source/WebKit/CMakeLists.txt:
Added an include path to WebKit/Shared/Extensions.

Canonical link: https://commits.webkit.org/266619@main