[JSC] Fix Air OptimizePairedLoadStore missing header includes https://bugs.webkit.org/show_bug.cgi?id=266936
Reviewed by Justin Michaud.

Fixes compile errors with non-unified build by adding missing include files for
single unit compilation.
Fixed compilation errors:

error: incomplete type 'JSC::CCallHelpers' named in nested name specifier
error: function 'JSC::B3::Air::Inst::forEachDefWithExtraClobberedRegs<JSC::B3::Air::Tmp, (lambda at ...)>' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage

* Source/JavaScriptCore/b3/air/AirOptimizePairedLoadStore.cpp

Canonical link: https://commits.webkit.org/272532@main