REGRESSION(r295627): [GCC] Unreviewed, fix build error in Debian Stable
error: call to non-'constexpr' function 'void WTF::isIntegralOrPointerType()'.

* Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp:
(WebCore::CSSPropertyParserHelpers::computeMinimumValue): Use
RELEASE_ASSERT_NOT_REACHED_UNDER_CONSTEXPR_CONTEXT

Canonical link: https://commits.webkit.org/251676@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@295671 268f45cc-cd09-0410-ab3c-d52691b4dbfc