REGRESSION(293530@main): WebKit/UIProcess/win/AutomationSessionClientWin.cpp: Unreviewed build fix https://bugs.webkit.org/show_bug.cgi?id=291060
> Source/WebKit/UIProcess/win/AutomationSessionClientWin.cpp(95,17): error: no viable conversion from 'const nullopt_t' to 'WebCore::MayNeedBeforeUnloadPrompt'

293530@main added a new member of type
WebCore::MayNeedBeforeUnloadPrompt to NavigationActionData.

* Source/WebKit/UIProcess/win/AutomationSessionClientWin.cpp:
(WebKit::AutomationSessionClient::requestNewPageWithOptions):

Canonical link: https://commits.webkit.org/293540@main