[MSVC] Suppress warning C4805: 'operation' : unsafe mix of type 'type' and type 'type' in operation https://bugs.webkit.org/show_bug.cgi?id=247024
Reviewed by Don Olmstead.

WinCairo EWS was failing to compile due to the following warning.

> WebCore\platform\graphics\angle\ANGLEUtilities.cpp(155): error C2220: the following warning is treated as an error
> WebCore\platform\graphics\angle\ANGLEUtilities.cpp(155): warning C4805: '==': unsafe mix of type 'GLboolean' and type 'bool' in operation

Other ports don't complain that. Suppress the warning C4805.

* Source/cmake/OptionsMSVC.cmake:

Canonical link: https://commits.webkit.org/255981@main